version: '3'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn start'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true